services:
  frontend:
      build:
        context: frontend
        target: builder
      ports:
        - 4200:4200
      stdin_open: true
      volumes:
        - ./frontend:/project
        - /project/node_modules
      restart: always
      networks:
        - angular-express
      depends_on:
        - backend
        
  backend:
    restart: always
    build:
      context: lac8r
      target: development
    volumes:
      - ./lac8r:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - angular-express
    ports:
      - 3000:3000

  mongo:
    restart: always
    image: mongo:6.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    ports:
      - 27018:27017
      
networks:
  angular-express:
  express-mongo: